### PR TITLE
initial commit for user's ORM

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Markelfdez — CHANGES_REQUESTED** [review]
SignInHistory must be deleted and the inheritance is not completed

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
_signInHistory_ was requested to be removed straight away from the model. 

The inheritance type we will use for this project will be an extesion.

**Comment by ghost** [comment]
added new changes, review pls

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
_user_ has some attributes that res.users already has.

**Comment by ghost** [comment]
change! removed duplicate fields

**Review by NicoRodBilbao — COMMENTED** [review]
Have you checked if it implements correctly onto odoo?

**Review by NicoRodBilbao — APPROVED** [review]

**Review by Markelfdez — APPROVED** [review]
okeyyy lets go

**Review by mlnnzr — APPROVED** [review]
It's ok

**Pull request merged**
